## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [1]:
import torch
import torch.nn as nn
from collections import OrderedDict


In [62]:
import torch.optim as optim

# Input data for Bit Addition gate
input_data = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
# Labels for Bit Addition gate
labels = torch.tensor([[0], [0.5], [0.5], [1]], dtype=torch.float32)


# Define the Perceptron class
class MyPerceptron1(nn.Module):
    def __init__(self, input_dim):
        super(MyPerceptron1, self).__init__()
        self.linear = nn.Linear(input_dim, 1)

    def forward(self, x):
        x = torch.sigmoid(self.linear(x))
        return x


# Define the stochastic gradient descent optimizer
perceptron = MyPerceptron1(input_dim=2)  # Input dimension for bit addition gate is 2

# Define the optimizer and the binary cross-entropy loss function.
optimizer = optim.SGD(perceptron.parameters(), lr=0.1)

loss_criterion = nn.BCELoss()



# Train the Perceptron model
num_epochs = 5000
for epoch in range(num_epochs):
    # Forward pass
    outputs = perceptron(input_data)
    # Calculate loss
    loss = loss_criterion(outputs, labels)
    
    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Print the loss every 100 epochs
    if (epoch + 1) % 500 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# Calculate predictions
predictions = perceptron(input_data)

correct_predictions = 0
threshold = 0.1

# Evaluate the model and calculate accuracy
for i, label in enumerate(labels):
    prediction = predictions[i]
    # Check if the prediction is within the threshold of the label
    if abs(prediction - label) < threshold:
        correct_predictions += 1

# Calculate the accuracy
accuracy = correct_predictions / len(labels)

# Print the accuracy
print(f'Accuracy: {accuracy*100:.0f}%')


print(f'Perceptron([0, 0]): {perceptron(input_data[0])}')
print(f'Perceptron([0, 1]): {perceptron(input_data[1])}')
print(f'Perceptron([1, 0]): {perceptron(input_data[2])}')
print(f'Perceptron([1, 1]): {perceptron(input_data[3])}')

print(input_data[0])


Epoch [500/5000], Loss: 0.4139
Epoch [1000/5000], Loss: 0.3802
Epoch [1500/5000], Loss: 0.3687
Epoch [2000/5000], Loss: 0.3629
Epoch [2500/5000], Loss: 0.3595
Epoch [3000/5000], Loss: 0.3573
Epoch [3500/5000], Loss: 0.3557
Epoch [4000/5000], Loss: 0.3545
Epoch [4500/5000], Loss: 0.3536
Epoch [5000/5000], Loss: 0.3529
Accuracy: 100%
Perceptron([0, 0]): tensor([0.0127], grad_fn=<SigmoidBackward0>)
Perceptron([0, 1]): tensor([0.5040], grad_fn=<SigmoidBackward0>)
Perceptron([1, 0]): tensor([0.5040], grad_fn=<SigmoidBackward0>)
Perceptron([1, 1]): tensor([0.9877], grad_fn=<SigmoidBackward0>)
tensor([0., 0.])


In [60]:
# your code here
#model1 = nn.Sequential(OrderedDict([
#    ('hidden', nn.
#]))

import torch.optim as optim

# Input data for Bit Addition gate
input_data = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
# Labels for Bit Addition gate
labels = torch.tensor([[0], [0.5], [0.5], [1]], dtype=torch.float32)

#Define hidden_size

# Define the Perceptron class
class MyPerceptron2(nn.Module):
    def __init__(self, input_dim, hidden_size):
        super(MyPerceptron2, self).__init__()
        self.layer1 = nn.Linear(input_dim, hidden_size)
        self.layer2 = nn.Linear(hidden_size, 1);

    def forward(self, x):
        x = torch.sigmoid(self.layer2(torch.sigmoid(self.layer1(x))))
        return x


# Define the stochastic gradient descent optimizer
perceptron = MyPerceptron2(input_dim=2, hidden_size=4)  # Input dimension for bit addition gate is 2

# Define the optimizer and the binary cross-entropy loss function.
optimizer = optim.SGD(perceptron.parameters(), lr=0.1)

loss_criterion = nn.BCELoss()



# Train the Perceptron model
num_epochs = 5000
for epoch in range(num_epochs):
    # Forward pass
    outputs = perceptron(input_data)
    # Calculate loss
    loss = loss_criterion(outputs, labels)
    
    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Print the loss every 100 epochs
    if (epoch + 1) % 500 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# Calculate predictions
predictions = perceptron(input_data)

correct_predictions = 0
threshold = 0.1

# Evaluate the model and calculate accuracy
for i, label in enumerate(labels):
    prediction = predictions[i]
    # Check if the prediction is within the threshold of the label
    if abs(prediction - label) < threshold:
        correct_predictions += 1

# Calculate the accuracy
accuracy = correct_predictions / len(labels)

# Print the accuracy
print(f'Accuracy: {accuracy*100:.0f}%')


print(f'Perceptron([0, 0]): {perceptron(input_data[0])}')
print(f'Perceptron([0, 1]): {perceptron(input_data[1])}')
print(f'Perceptron([1, 0]): {perceptron(input_data[2])}')
print(f'Perceptron([1, 1]): {perceptron(input_data[3])}')

print(input_data[0])


Epoch [500/5000], Loss: 0.5337
Epoch [1000/5000], Loss: 0.4173
Epoch [1500/5000], Loss: 0.3823
Epoch [2000/5000], Loss: 0.3688
Epoch [2500/5000], Loss: 0.3622
Epoch [3000/5000], Loss: 0.3584
Epoch [3500/5000], Loss: 0.3560
Epoch [4000/5000], Loss: 0.3544
Epoch [4500/5000], Loss: 0.3532
Epoch [5000/5000], Loss: 0.3523
Accuracy: 100%
Perceptron([0, 0]): tensor([0.0105], grad_fn=<SigmoidBackward0>)
Perceptron([0, 1]): tensor([0.5012], grad_fn=<SigmoidBackward0>)
Perceptron([1, 0]): tensor([0.5013], grad_fn=<SigmoidBackward0>)
Perceptron([1, 1]): tensor([0.9877], grad_fn=<SigmoidBackward0>)
tensor([0., 0.])


In [59]:
# your code here
#model1 = nn.Sequential(OrderedDict([
#    ('hidden', nn.
#]))

import torch.optim as optim

# Input data for Bit Addition gate
input_data = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
# Labels for Bit Addition gate
labels = torch.tensor([[0], [0.5], [0.5], [1]], dtype=torch.float32)

#Define hidden_size

# Define the Perceptron class
class MyPerceptron3(nn.Module):
    def __init__(self, input_dim, hidden_size):
        super(MyPerceptron3, self).__init__()
        self.layer1 = nn.Linear(input_dim, hidden_size)
        self.layer2 = nn.Linear(hidden_size, 1);

    def forward(self, x):
        x = torch.sigmoid(self.layer2(torch.sigmoid(self.layer1(x))))
        return x


# Define the stochastic gradient descent optimizer
perceptron = MyPerceptron3(input_dim=2, hidden_size=4)  # Input dimension for bit addition gate is 2

# Define the optimizer and the binary cross-entropy loss function.
optimizer = optim.SGD(perceptron.parameters(), lr=0.1)

loss_criterion = nn.MSELoss()



# Train the Perceptron model
num_epochs = 5000
for epoch in range(num_epochs):
    # Forward pass
    outputs = perceptron(input_data)
    # Calculate loss
    loss = loss_criterion(outputs, labels)
    
    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Print the loss every 100 epochs
    if (epoch + 1) % 500 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# Calculate predictions
predictions = perceptron(input_data)

correct_predictions = 0
threshold = 0.1

# Evaluate the model and calculate accuracy
for i, label in enumerate(labels):
    prediction = predictions[i]
    # Check if the prediction is within the threshold of the label
    if abs(prediction - label) < threshold:
        correct_predictions += 1

# Calculate the accuracy
accuracy = correct_predictions / len(labels)

# Print the accuracy
print(f'Accuracy: {accuracy*100:.0f}%')


print(f'Perceptron([0, 0]): {perceptron(input_data[0])}')
print(f'Perceptron([0, 1]): {perceptron(input_data[1])}')
print(f'Perceptron([1, 0]): {perceptron(input_data[2])}')
print(f'Perceptron([1, 1]): {perceptron(input_data[3])}')

print(input_data[0])


Epoch [500/5000], Loss: 0.0861
Epoch [1000/5000], Loss: 0.0431
Epoch [1500/5000], Loss: 0.0199
Epoch [2000/5000], Loss: 0.0109
Epoch [2500/5000], Loss: 0.0069
Epoch [3000/5000], Loss: 0.0049
Epoch [3500/5000], Loss: 0.0037
Epoch [4000/5000], Loss: 0.0029
Epoch [4500/5000], Loss: 0.0024
Epoch [5000/5000], Loss: 0.0020
Accuracy: 100%
Perceptron([0, 0]): tensor([0.0576], grad_fn=<SigmoidBackward0>)
Perceptron([0, 1]): tensor([0.5037], grad_fn=<SigmoidBackward0>)
Perceptron([1, 0]): tensor([0.5035], grad_fn=<SigmoidBackward0>)
Perceptron([1, 1]): tensor([0.9315], grad_fn=<SigmoidBackward0>)
tensor([0., 0.])
